name: Autocoder Bot

on:
  issues:
    types: [opened, reopened, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-code-and-pr:
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x ./scripts/script.sh

      - name: Run interaction script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          ISSUE_NUM: ${{ github.event.issue.number }}
          OPENAI_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: ./scripts/script.sh "$GH_TOKEN" "$REPO" "$ISSUE_NUM" "$OPENAI_KEY"

      - name: Configure git
        run: |
          git config --global user.name "autocoder-bot"
          git config --global user.email "actions@github.com"

      - name: Commit files
        run: |
          git add .
          git commit -m "feat: Add generated code for issue #${{ github.event.issue.number }}" || echo "No changes to commit"

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "feat: Add generated code for issue #${{ github.event.issue.number }}"
          title: "Autocode: Fixes issue #${{ github.event.issue.number }}"
          body: |
            This PR was auto-generated by the autocoder-bot.
            It addresses issue #${{ github.event.issue.number }}.
          committer: autocoder-bot <actions@github.com>
          author: autocoder-bot <actions@github.com>
          branch: autocoder-branch-${{ github.event.issue.number }}
          base: main
          labels: autocoder-bot
